[variables]
NODE_ENV = "production"

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build", "npx prisma generate"]

[start]
cmd = "npm run migrate:prod && npm run seed && npm run import -- --type paints --file data/arcturus-paints.json && npm start"
